# Generated by Django 5.2.4 on 2025-07-23 06:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('std_class', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A+', 'Excellent'), ('A', 'Very Good'), ('B', 'Good'), ('C', 'Average'), ('D', 'Below Average'), ('F', 'Fail')], max_length=2)),
                ('activities', models.CharField(choices=[('sports', 'Sports'), ('music', 'Music'), ('dance', 'Dance'), ('drama', 'Drama'), ('nss', 'NSS'), ('scouts', 'Scouts & Guides'), ('art', 'Art & Craft'), ('coding', 'Coding Club'), ('literature', 'Literary Club')], max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='student_site.students')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('KA', 'Karnataka'), ('MH', 'Maharashtra'), ('DL', 'Delhi'), ('TN', 'Tamil Nadu'), ('GJ', 'Gujarat')], max_length=2)),
                ('country', models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia')], default='IN', max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='student_site.students')),
            ],
        ),
    ]
