# Generated by Django 5.2.4 on 2025-07-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
        migrations.AlterModelTable(
            name='extracurricular',
            table='ExtraCurricular',
        ),
        migrations.AlterModelTable(
            name='students',
            table='Students',
        ),
    ]
