# Generated by Django 5.2.4 on 2025-07-23 07:19

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_site', '0002_alter_address_table_alter_extracurricular_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+911234567890', max_length=128, region=None, unique=True),
        ),
    ]
