# Generated by Django 5.2.4 on 2025-07-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_site', '0004_students_dob_alter_students_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Select your blood group', max_length=3, null=True),
        ),
    ]
